# Ein Secret mit Benutzername und Kennwort für die Datenbank im Backend.
apiVersion: v1
kind: Secret
metadata:
  name: secret-wp-db
  namespace: backend
type: Opaque
data:
  # verySecret
  rootPassword: dmVyeVNlY3JldA==
  # wp
  username: d3AK
  # secretWp
  password: c2VjcmV0V3A=
---
# Ein weiteres Secret mit Benutzername und Kennwort für das Frontend.
# Wegen der Trennung in Namespaces ist das hier doppelt.
apiVersion: v1
kind: Secret
metadata:
  name: secret-wp-fe
  namespace: frontend
type: Opaque
data:
  username: d3AK
  password: c2VjcmV0V3A=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-wp-fe
  namespace: frontend
data:
  WORDPRESS_DB_HOST: wp-database.backend
  WORDPRESS_DB_NAME: wp
